const {
  GraphQLObjectType,
  GraphQLString,
  GraphQLSchema,
  GraphQLList,
  GraphQLEnumType,
  GraphQLInt,
} = require('graphql');

module.exports.DailyDataInput = new GraphQLEnumType({
  name: 'DailyDataInput',
  description: 'Accepts either STATION_NAME or stationNumber (preceded by an underscore).',
  values: {
    CORK_AIRPORT: { value: 3904, description: 'stationNumber: 3904' },
    _3904: {value: 3904, description: 'station: CORK_AIRPORT'},
    MOORE_PARK: { value: 575, description: 'stationNumber:  575' },
    _575: {value: 575, description: 'station: MOORE_PARK'},
    ROCHES_POINT: { value: 1075, description: 'stationNumber: 1075' },
    _1075: {value: 1075, description: 'station: ROCHES_POINT'},
    SHERKIN_ISLAND: { value: 775, description: 'stationNumber:  775' },
    _775: {value: 775, description: 'station: SHERKIN_ISLAND'},
    VALENTIA_OBSERVATORY: { value: 2275, description: 'stationNumber: 2275' },
    _2275: {value: 2275, description: 'station: VALENTIA_OBSERVATORY'},
    GURTEEN: { value: 1475, description: 'stationNumber: 1475' },
    _1475: {value: 1475, description: 'station: GURTEEN'},
    SHANNON_AIRPORT: { value: 518, description: 'stationNumber:  518' },
    _518: {value: 518, description: 'station: SHANNON_AIRPORT'},
    JOHNSTOWN_CASTLE: { value: 1775, description: 'stationNumber: 1775' },
    _1775: {value: 1775, description: 'station: JOHNSTOWN_CASTLE'},
    OAK_PARK: { value: 375, description: 'stationNumber:  375' },
    _375: {value: 375, description: 'station: OAK_PARK'},
    CASEMENT: { value: 3723, description: 'stationNumber: 3723' },
    _3723: {value: 3723, description: 'station: CASEMENT'},
    DUBLIN_AIRPORT: { value: 532, description: 'stationNumber:  532' },
    _532: {value: 532, description: 'station: DUBLIN_AIRPORT'},
    PHOENIX_PARK: { value: 175, description: 'stationNumber:  175' },
    _175: {value: 175, description: 'station: PHOENIX_PARK'},
    DUNSANY: { value: 1375, description: 'stationNumber: 1375' },
    _1375: {value: 1375, description: 'station: DUNSANY'},
    MULLINGAR: { value: 875, description: 'stationNumber: 875' },
    _875: {value: 875, description: 'station: MULLINGAR'},
    ATHENRY: { value: 1875, description: 'stationNumber: 1875' },
    _1875: {value: 1875, description: 'station: ATHENRY'},
    MACE_HEAD: { value: 275, description: 'stationNumber:  275' },
    _275: {value: 275, description: 'station: MACE_HEAD'},
    MT_DILLON: { value: 1975, description: 'stationNumber: 1975' },
    _1975: {value: 1975, description: 'station: MT_DILLON'},
    BELMULLET: { value: 2375, description: 'stationNumber: 2375' },
    _2375: {value: 2375, description: 'station: BELMULLET'},
    CLAREMORRIS: { value: 2175, description: 'stationNumber: 2175' },
    _2175: {value: 2175, description: 'station: CLAREMORRIS'},
    KNOCK_AIRPORT: { value: 4935, description: 'stationNumber: 4935' },
    _4935: {value: 4935, description: 'station: KNOCK_AIRPORT'},
    NEWPORT_FURNACE: { value: 833, description: 'stationNumber:  833' },
    _833: {value: 833, description: 'station: NEWPORT_FURNACE'},
    MARKREE: { value: 1275, description: 'stationNumber: 1275' },
    _1275: {value: 1275, description: 'station: MARKREE'},
    BALLYHAISE: { value: 675, description: 'stationNumber:  675' },
    _675: {value: 675, description: 'station: BALLYHAISE'},
    FINNER: { value: 2075, description: 'stationNumber: 2075' },
    _2075: {value: 2075, description: 'station: FINNER'},
    MALIN_HEAD: { value: 1575, description: 'stationNumber: 1575' },
    _1575: {value: 1575, description: 'station: MALIN_HEAD'},
  },
});

// Good for monthly, today's and yesterday's data. Doesn't make sense that this is called StationsInput anymore. TODO
module.exports.StationsInput = new GraphQLEnumType({
  name: 'StationsInput',
  values: {
    VALENTIA_OBSERVATORY: { value: 'valentia' },
    SHERKIN_ISLAND: { value: 'sherkin-island' },
    SHANNON_AIRPORT: { value: 'shannon' },
    ROCHES_POINT: { value: 'roches-point' },
    PHOENIX_PARK: { value: 'phoenix-park' },
    OAK_PARK: { value: 'oak-park' },
    NEWPORT_FURNACE: { value: 'newport-furnace' },
    MULLINGAR: { value: 'newport-furnace' },
    MOUNT_DILLON: { value: 'mt-dillon' },
    MOORE_PARK: { value: 'moore-parkk' },
    MARKREE_CASTLE: { value: 'Markree-Castle' },
    MALIN_HEAD: { value: 'malin-head' },
    MACE_HEAD: { value: 'mace-head' },
    KNOCK_AIRPORT: { value: 'knock' },
    JOHNSTOWN_CASTLE: { value: 'johnstown' },
    GURTEEN: { value: 'gurteen' },
    FINNER_CAMP: { value: 'finner' },
    DUNSANY_GRANGE: { value: 'dunsany' },
    CORK_AIRPORT: { value: 'cork' },
    CLAREMORRIS: { value: 'claremorris' },
    CASEMENT_AERODROME: { value: 'casement' },
    BELMULLET: { value: 'belmullet' },
    BALLYHAISE: { value: 'ballyhaise' },
    ATHENRY: { value: 'athenry' },
    DUBLIN_AIRPORT: { value: 'dublin' },
  },
});

module.exports.RegionsInput = new GraphQLEnumType({
  name: 'RegionsInput',
  values: {
    CONNAUGHT: { value: 'Connacht' }, // this is how MÉ spell it, must have capital letter!
    ULSTER: { value: 'Ulster' }, // must have capital letter.
    LEINSTER: { value: 'Leinster' }, // must have capital letter.
    MUNSTER: { value: 'Munster' }, // must have capital letter.
    DUBLIN: { value: 'Dublin' }, // must have capital letter.
  },
});

module.exports.TimesInput = new GraphQLEnumType({
  name: 'TimesInput',
  description: "Reports are hourly. Eg _1 = '01:00'",
  values: {
    _1: { value: '01:00' },
    _2: { value: '02:00' },
    _3: { value: '03:00' },
    _4: { value: '04:00' },
    _5: { value: '05:00' },
    _6: { value: '06:00' },
    _7: { value: '07:00' },
    _8: { value: '08:00' },
    _9: { value: '09:00' },
    _10: { value: '10:00' },
    _11: { value: '11:00' },
    _12: { value: '12:00' },
    _13: { value: '13:00' },
    _14: { value: '14:00' },
    _15: { value: '15:00' },
    _16: { value: '16:00' },
    _17: { value: '17:00' },
    _18: { value: '18:00' },
    _19: { value: '19:00' },
    _20: { value: '20:00' },
    _21: { value: '21:00' },
    _22: { value: '22:00' },
    _23: { value: '23:00' },
    _00: { value: '00:00' },
  },
});

module.exports.StationDetailInput = new GraphQLEnumType({
  name: 'StationDetailInput',
  description: 'Open or closed, defaults to all',
  values: {
    OPEN: { value: 'OPEN' },
    CLOSED: { value: 'CLOSED' },
    ALL: { value: 'ALL' },
    MAIN: { value: 'MAIN' },
  },
});
module.exports.LocationsInput = new GraphQLEnumType({
  name: 'LocationsInput',
  values: {
    CORK: { value: 'Cork' },
    GALWAY: { value: 'Galway' },
    MAYO: { value: 'Mayo' },
    DONEGAL: { value: 'Donegal' },
    KERRY: { value: 'Kerry' },
    TIPPERARY: { value: 'Tipperary' },
    CLARE: { value: 'Clare' },
    LIMERICK: { value: 'Limerick' },
    ROSCOMMON: { value: 'Roscommon' },
    WEXFORD: { value: 'Wexford' },
    MEATH: { value: 'Meath' },
    KILKENNY: { value: 'Kilkenny' },
    WICKLOW: { value: 'Wicklow' },
    OFFALY: { value: 'Offaly' },
    CAVAN: { value: 'Cavan' },
    WATERFORD: { value: 'Waterford' },
    WESTMEATH: { value: 'Westmeath' },
    SLIGO: { value: 'Sligo' },
    LAOIS: { value: 'Laois' },
    KILDARE: { value: 'Kildare' },
    LEITRIM: { value: 'Leitrim' },
    MONAGHAN: { value: 'Monaghan' },
    LONGFORD: { value: 'Longford' },
    DUBLIN: { value: 'Dublin' },
    CARLOW: { value: 'Carlow' },
    LOUTH: { value: 'Louth' },
    BELFAST: { value: 'Belfast' },
  },
});

module.exports.PresentObservationsInput = new GraphQLEnumType({
  name: 'presentObservationsInput',
  values: {
    ATHENRY: { value: 'Athenry' },
    BALLYHAISE: { value: 'Ballyhaise' },
    BELMULLET: { value: 'Belmullet' },
    CASEMENT: { value: 'Casement' },
    CLAREMORRIS: { value: 'Claremorris' },
    CORK: { value: 'Cork' },
    DUBLIN: { value: 'Dublin' },
    DUNSANY: { value: 'Dunsany' },
    FINNER: { value: 'Finner' },
    GURTEEN: { value: 'Gurteen' },
    JOHNSTOWN_CASTLE: { value: 'Johnstown Castle' },
    KNOCK: { value: 'Knock' },
    MACE_HEAD: { value: 'Mace Head' },
    MALIN_HEAD: { value: 'Malin Head' },
    MARKREE_CASTLE: { value: 'Markree Castle' },
    MOORE_PARK: { value: 'Moore Park' },
    MT_DILLON: { value: 'Mt Dillon' },
    MULLINGAR: { value: 'Mullingar' },
    NEWPORT_MAYO: { value: 'NewportMayo' },
    OAK_PARK: { value: 'Oak Park' },
    PHOENIX_PARK: { value: 'Phoenix Park' },
    ROCHES_POINT: { value: "Roche's Point" },
    SHANNON: { value: 'Shannon' },
    SHERKIN_ISLAND: { value: 'Sherkin Island' },
    VALENTIA: { value: 'Valentia' },
  },
});

module.exports.monthlyWeatherStationInput = new GraphQLEnumType({
  name: 'monthlyWeatherStationInput',
  values: {
    ATHENRY: { value: 'Athenry' },
    BALLYHAISE: { value: 'Ballyhaise' },
    BELMULLET: { value: 'Belmullet' },
    CASEMENT: { value: 'Casement' },
    CLAREMORRIS: { value: 'Claremorris' },
    CORK: { value: 'Cork' },
    DUBLIN: { value: 'Dublin' },
    DUNSANY: { value: 'Dunsany' },
    FINNER: { value: 'Finner' },
    GURTEEN: { value: 'Gurteen' },
    JOHNSTOWN_CASTLE: { value: 'Johnstown Castle' },
    KNOCK: { value: 'Knock' },
    MACE_HEAD: { value: 'Mace Head' },
    MALIN_HEAD: { value: 'Malin Head' },
    MARKREE_CASTLE: { value: 'Markree Castle' },
    MOORE_PARK: { value: 'Moore Park' },
    MT_DILLON: { value: 'Mt Dillon' },
    MULLINGAR: { value: 'Mullingar' },
    NEWPORT_MAYO: { value: 'NewportMayo' },
    OAK_PARK: { value: 'Oak Park' },
    PHOENIX_PARK: { value: 'Phoenix Park' },
    ROCHES_POINT: { value: "Roche's Point" },
    SHANNON: { value: 'Shannon' },
    SHERKIN_ISLAND: { value: 'Sherkin Island' },
    VALENTIA: { value: 'Valentia' },
  },
});

module.exports.CountyForecastInput = new GraphQLEnumType({
  name: 'CountyForecastInput',
  values: {
    DUBLIN: { value: 'DUBLIN' },
    WEXFORD: { value: 'WEXFORD' },
    CORK: { value: 'CORK' },
    KERRY: { value: 'KERRY' },
    GALWAY: { value: 'GALWAY' },
    OFFALY: { value: 'OFFALY' },
    MAYO: { value: 'MAYO' },
    DONEGAL: { value: 'DONEGAL' },
    KILDARE: { value: 'KILDARE' },
    KILKENNY: { value: 'KILKENNY' },
    CARLOW: { value: 'CARLOW' },
    MONAGHAN: { value: 'MONAGHAN' },
    CAVAN: { value: 'CAVAN' },
    WESTMEATH: { value: 'WESTMEATH' },
    CLARE: { value: 'CLARE' },
    MEATH: { value: 'MEATH' },
    SLIGO: { value: 'SLIGO' },
    LAOIS: { value: 'LAOIS' },
    LOUTH: { value: 'LOUTH' },
    WATERFORD: { value: 'WATERFORD' },
    TIPPERARY: { value: 'TIPPERARY' },
    ROSCOMMON: { value: 'ROSCOMMON' },
    WICKLOW: { value: 'WICKLOW' },
    LONGFORD: { value: 'LONGFORD' },
    LEITRIM: { value: 'LEITRIM' },
    LIMERICK: { value: 'LIMERICK' },
  },
});

module.exports.DataTimeFrameInput = new GraphQLEnumType({
  name: 'DataTimeFrameInput',
  values: {
    DAILY: { value: 'dly' },
    MONTHLY: { value: 'mly' },
  },
});
